carrinho/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.resumo_carrinho, name="resumo_carrinho"),
    path('add/', views.adicionar_carrinho, name="adicionar_carrinho"),
    path('delete/', views.deletar_carrinho, name="deletar_carrinho"),
    path('update/', views.atualizar_carrinho, name="atualizar_carrinho"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('produtos.urls')),
    path('carrinho/',include('carrinho.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

produtos/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('vermaisproduto/<int:id>/',views.vermaisproduto, name='vermaisproduto'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_password/', views.update_password, name='update_password'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
]

produtos/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	date_modified = models.DateTimeField(User, auto_now=True)
	phone = models.CharField(max_length=20, blank=True)
	old_cart = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.user.username
     
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

    post_save.connect(create_profile, sender=User)



class Cliente(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	phone = models.CharField(max_length=10)
	email = models.EmailField(max_length=100)
	password = models.CharField(max_length=100)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'
     

class Categoria(models.Model):
    nome = models.CharField(max_length=65, blank=True, null=True)

    def __str__(self):
        return self.nome

class Produto(models.Model):
    nome = models.CharField(max_length=80, blank=True, null=True)
    descricao = models.TextField(blank=True, null=True)
    preco = models.DecimalField(default=0, max_digits=10, decimal_places=2, blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, blank=True, null=True)
    capa = models.ImageField(upload_to='capa/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.nome

class Pedido(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, blank=True, null=True)
    cliente= models.ForeignKey(Cliente,on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=1, blank=True, null=True)
    endereco = models.TextField()
    telefone = models.CharField(max_length=20, blank=True, null=True)
    data = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.produto

produtos/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django import forms
from .models import Profile

class UserInfoForm(forms.ModelForm):
    phone = forms.CharField(
        label="", 
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone'}), 
        required=False
    )

    class Meta:
        model = Profile
        fields = ('phone',)

class ChangePasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Password'
        })
        self.fields['new_password1'].label = ''
        self.fields['new_password1'].help_text = '''
            <ul class="form-text text-muted small">
                <li>Sua senha não pode ser muito similar a outras informações pessoais.</li>
                <li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                <li>Sua senha não pode ser uma senha comum.</li>
                <li>Sua senha não pode ser inteiramente numérica.</li>
            </ul>
        '''

        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Confirmar Senha'
        })
        self.fields['new_password2'].label = ''
        self.fields['new_password2'].help_text = '''
            <span class="form-text text-muted">
                <small>Digite a mesma senha para verificação.</small>
            </span>
        '''

class UpdateUserForm(UserChangeForm):
    password = None
    email = forms.EmailField(
        label="", 
        widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'email'}), 
        required=False
    )
    first_name = forms.CharField(
        label="", 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'nome'}), 
        required=False
    )
    last_name = forms.CharField(
        label="", 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'sobrenome'}), 
        required=False
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Nome de Usuário'
        })
        self.fields['username'].label = ''
        self.fields['username'].help_text = '''
            <span class="form-text text-muted">
                <small>Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.</small>
            </span>
        '''

class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="", 
        widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'})
    )
    first_name = forms.CharField(
        label="", 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Nome'})
    )
    last_name = forms.CharField(
        label="", 
        max_length=100,
        widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Sobrenome'})
    )

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Nome de Usuário'
        })
        self.fields['username'].label = ''
        self.fields['username'].help_text = '''
            <span class="form-text text-muted">
                <small>Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.</small>
            </span>
        '''

        self.fields['password1'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Senha'
        })
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '''
            <ul class="form-text text-muted small">
                <li>Sua senha não pode ser muito similar a outras informações pessoais.</li>
                <li>Sua senha precisa conter pelo menos 8 caracteres.</li>
                <li>Sua senha não pode ser uma senha comum.</li>
                <li>Sua senha não pode ser inteiramente numérica.</li>
            </ul>
        '''

        self.fields['password2'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Confirmar Senha'
        })
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '''
            <span class="form-text text-muted">
                <small>Digite a mesma senha para verificação.</small>
            </span>
        '''

produtos/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Produto,Categoria
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .forms import SignUpForm

def home(request):
    produto = Produto.objects.all()
    categoria = Categoria.objects.all()
    return render(request,'pages/home.html',{'produto':produto,'categoria':categoria})

def vermaisproduto(request, id):
    produto = Produto.objects.get(pk=id)
    categoria = produto.categoria
    produtos_relacionados = Produto.objects.filter(categoria=categoria).exclude(pk=id)
    return render(request,'pages/vermaisproduto.html',{'produto':produto,'produtos_relacionados': produtos_relacionados})


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        senha = request.POST['senha']
        user = authenticate(request,username=username,password=senha)
        if user is not None:
            login(request,user)
            return redirect(reverse('home'))
        else:
            return render(request,"pages/login.html")
    return render(request,"pages/login.html",{})

def logout_user(request):
    request.session.flush()
    return redirect(reverse('home'))

def register_user(request):
    form = SignUpForm
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            
            user = authenticate(username=username,password=password)

            login(request,user)

            return redirect("home")

    return render(request,"pages/cadastro.html",{"form":form})

def update_password(request):
    pass

def update_user(request):
    pass

def update_info(request):
    pass

produtos/templates/pages/cadastro.html
{% include "partials/head.html" %}

<body>
    
    <div class="container">
        <h2>Cadastro</h2>

        <form method="POST" action="{% url "register" %}" >
            {% csrf_token %}
            
            <div class="form-group">
                {{form.as_p}}
            </div>
            
            <input type="submit" value="Cadastrar">
        </form>
    </div>
</body>
</html>

produtos/templates/pages/home.html
{% include "partials/head.html" %}

<body>
    {% include "partials/header.html" %}
    {% include "partials/menu.html" %}

    <main class="main-content-container">
        <div class="main-content main-content-list container">
            {% for categoria in categoria %}
                <div class="category">
                    <h1>{{ categoria.nome }}</h1>

                    <div class="products">
                        {% for produto in categoria.produto_set.all %}
                            {% include "partials/produto.html" %}
                        {% empty %}
                            <p>Não há produtos nesta categoria.</p>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </main>
</body>
</html>

produtos/templates/pages/login.html
{% include "partials/head.html" %}
<body>
    <div class="container">
        <h2>Login</h2>

        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                <input name="username" class="form-control" type="text" placeholder="nome...">
            </div>
            <div class="form-group">
                <input name="senha" class="form-control" type="password" placeholder="Senha...">
            </div>
            <input class="btn btn-info btn-lg" type="submit" value="Enviar">
        </form>


    </div>
</body>
</html>

produtos/templates/pages/vermaisproduto.html
{% include "partials/head.html" %}
{% include "partials/header2.html" %}

<div class="product-details-container">
    <div class="product-details-header">
        <div class="product-details-title"><h1>{{ produto.nome }}</h1></div>
        {% if produto.capa and produto.capa.url %}
            <img class="product-details-image" src="{{ produto.capa.url }}" alt="capa">
        {% endif %}
    </div>

    <!-- Detalhes do Produto -->
    <div class="product-details-info">
        <p class="product-details-description">{{ produto.descricao }}</p>
        <p class="product-details-price">R${{ produto.preco }}</p>
        <div class="product-quantity-label"><span>Quantidade:</span></div>
        <div class="product-quantity-selector">
            <select class="quantity-dropdown" id="qty-cart">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>

        <a href= ""><button value="{{produto.id}}"class="product-details-add-to-cart-btn" id="add-carrinho">Adicionar ao Carrinho</button></a>
    </div>
</div>

<div class="footer-vermaisproduto">
    <h1>Produtos relacionados</h1>
    <div>
        {% for produto in produtos_relacionados %}
            {% include "partials/produto.html" %}
        {% endfor %}
    </div>
</div>


<script>
    // Check if button pressed
    $(document).on('click', '#add-carrinho', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url 'adicionar_carrinho' %}',
            data: {
               produto_id: $('#add-carrinho').val(),
               produto_qty:$('#qty-cart option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
    
            success: function(json){
                //console.log(json)
                document.getElementById('quantidade_carrinho').textContent = json.qant
            },
    
            error: function(xhr, errmsg, err){
    
            }
    
    
        });
    
    
    
    })
    
    </script>